export const products = [
    {
        "type": "Heading One",
        "class":"h1",
        "size": "2.5rem/40px",
        "weight": "Semibold",
        "code": "h1",
        "region": "NY - Southeast",
        "nextCoverageDate": "02/27/2020",
        "endCoverageDate": "05/29/2020",
        "recruiter": "Cora Kelly",
        "Call to Action": "View Details"
    },
    {
        "type": "Heading Two",
        "class":"h2",
        "size": "2.2rem/35.2px",
        "weight": "Regular",
        "code": "h2",
        "specialty": "Psychiatry",
        "state": "NY",
        "region": "NY - Southeast",
        "nextCoverageDate": "03/04/2020",
        "endCoverageDate": "03/31/2020",
        "recruiter": "Cora Kelly",
        "Call to Action": "View Details"
    },
    {
        "type": "Heading Three",
        "class":"h3",
        "size": "1.9rem/30.4px",
        "weight": "Regular",
        "code": "h3",
        "state": "NY",
        "region": "NY - Manhattan",
        "nextCoverageDate": "03/04/2020",
        "endCoverageDate": "06/30/2020",
        "recruiter": "Cora Kelly",
        "Call to Action": "View Details"
    },
    {
        "type": "Heading Four",
        "class":"h4",
        "size": "1.5rem/24px",
        "weight": "Regular",
        "code": "h4",
        "state": "NY",
        "region": "NY - Northwest",
        "nextCoverageDate": "03/04/2020",
        "endCoverageDate": "06/30/2020",
        "recruiter": "Elisa Doe",
        "Call to Action": "View Details"
    },
    {
        "type": "Heading Five",
        "class":"h5",
        "size": "1.25rem/20px",
        "weight": "Regular",
        "code": "h5",
        "state": "NY",
        "region": "NY - Northwest",
        "nextCoverageDate": "03/04/2020",
        "endCoverageDate": "06/30/2020",
        "recruiter": "Elisa Doe",
        "Call to Action": "View Details"
    },
    {
        "type": "Heading Six",
        "class":"h6",
        "size": "1rem/16px",
        "weight": "Regular",
        "code": "h6",
        "state": "NY",
        "region": "NY - Northwest",
        "nextCoverageDate": "03/04/2020",
        "endCoverageDate": "06/30/2020",
        "recruiter": "Elisa Doe",
        "Call to Action": "View Details"
    },
    {
        "type": "Body",
        "class":"atlas-body-text",
        "size": "1rem/16px",
        "weight": "Regular",
        "code": "p",
        "state": "NY",
        "region": "NY - Southeast",
        "nextCoverageDate": "03/04/2020",
        "endCoverageDate": "06/30/2020",
        "recruiter": "April Marks",
        "Call to Action": "View Details"
    },
    {
        "type": "Link",
        "size": "1rem/16px",
        "weight": "Regular",
        "state": "NY",
        "region": "NY - Southeast",
        "nextCoverageDate": "03/04/2020",
        "endCoverageDate": "06/23/2020",
        "recruiter": "April Marks",
        "Call to Action": "View Details"
    },
    {
        "type": "Card Titles",
        "size": "1rem/16px",
        "class":"atlas-card-title",
        "weight": "Semibold",
        "state": "NY",
        "region": "NY - Southeast",
        "nextCoverageDate": "03/04/2020",
        "endCoverageDate": "04/30/2020",
        "recruiter": "April Marks",
        "Call to Action": "View Details"
    },
    {
        "type": "Small Text",
        "size": ".95rem/15.2px",
        "class":"atlas-small-text",
        "weight": "Regular",
        "state": "NY",
        "region": "NY - Southeast",
        "nextCoverageDate": "03/04/2020",
        "endCoverageDate": "05/29/2020",
        "recruiter": "April Marks",
        "Call to Action": "View Details"
    },
    {
        "type": "Smaller Text",
        "size": ".9rem/14.4px",
        "class":"atlas-smaller-text",
        "weight": "Regular",
        "state": "NY",
        "region": "NY - Southeast",
        "nextCoverageDate": "03/04/2020",
        "endCoverageDate": "05/29/2020",
        "recruiter": "April Marks",
        "Call to Action": "View Details"
    },
    {
        "type": "Smallest Text",
        "class":"atlas-smallest-text",
        "size": ".85rem/13.6px",
        "weight": "Regular",
        "state": "NY",
        "region": "NY - Southeast",
        "nextCoverageDate": "03/04/2020",
        "endCoverageDate": "05/29/2020",
        "recruiter": "April Marks",
        "Call to Action": "View Details"
    }
];
